;;; yeetube.el --- Scrape YouTube, Play with mpv & Download with yt-dlp  -*- lexical-binding: t; -*-

;; Copyright (C) 2023-2024  Thanos Apollo

;; Author: Thanos Apollo <public@thanosapollo.org>
;; Keywords: extensions youtube videos
;; URL: https://thanosapollo.org/projects/yeetube/
;; Version: 2.3.1

;; Package-Requires: ((emacs "29.1") (compat "29.1.4.2") (keymap-popup "0.2.0"))

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; This package provides the ability to scrape YouTube, with the results
;; displayed in a tabulated list.
;;
;; Core features include:
;;
;; - Executing YouTube queries
;; - Playing videos, by default using MPV
;; - Downloading videos, using yt-dlp
;; - Bookmarking and saving video URLs
;; - A standalone, minimalist yt-dlp frontend

;;; Code:

(require 'compat)
(require 'url)
(require 'cl-lib)
(require 'socks)
(require 'url-handlers)
(require 'xdg)
(require 'subr-x)

(require 'keymap-popup)
(require 'yeetube-backend)
(require 'yeetube-youtube)
(require 'yeetube-ui)
(require 'yeetube-mpv)
(require 'yeetube-download)

(defgroup yeetube nil
  "Youtube Front-End."
  :group 'external
  :prefix "yeetube-")

(defcustom yeetube-torsocks-program (and (executable-find "torsocks") "torsocks")
  "Path for torsocks executable."
  :type '(choice (const :tag "Not found" nil) string))

(defcustom yeetube-ytdlp-program (and (executable-find "yt-dlp") "yt-dlp")
  "Path for yt-dlp executable."
  :type '(choice (const :tag "Not found" nil) string))

(defcustom yeetube-results-limit 20
  "Define a limit for search results."
  :type 'natnum)

(defcustom yeetube-play-function #'yeetube-mpv-play
  "Select media player function."
  :type 'function)

(defcustom yeetube-download-audio-format nil
  "Download videos as specified audio only formats."
  :type '(radio (const :tag "None" nil)
		(const :tag "AAC" "aac")
		(const :tag "ALAC" "alac")
		(const :tag "FLAC" "flac")
		(const :tag "M4A" "m4a")
		(const :tag "MP3" "mp3")
		(const :tag "OPUS" "opus")
		(const :tag "Vorbis" "vorbis")
		(const :tag "WAV" "wav")))

(defcustom yeetube-download-directory (or (xdg-user-dir "DOWNLOAD") (getenv "HOME"))
  "Default directory to download videos."
  :type 'string)

(defcustom yeetube-default-sort-column nil
  "Column to sort the search results table."
  :type '(radio (const :tag "None" nil)
		(const "Title")
                (const "Views")
                (const "Duration")
                (const "Channel")))

(defcustom yeetube-default-sort-ascending nil
  "Whether to sort the search results in ascending order."
  :type 'boolean)

(defcustom yeetube-enable-tor nil
  "Enable routing through tor."
  :type 'boolean)

(defcustom yeetube-enable-emojis (and (char-displayable-p ?\N{GRINNING FACE}) t)
  "Enable emojis in *yeetube* buffer."
  :type 'boolean)

(defcustom yeetube-pop-to-same-window-p t
  "When non-nil, create *yeetube* buffer at the same window."
  :type 'boolean)

(defcustom yeetube-thumbnail-size '(120 . 90)
  "Thumbnail size (width . height)."
  :type '(cons integer integer))

(defcustom yeetube-display-thumbnails-p t
  "When non-nil, fetch & display thumbnails."
  :type 'boolean)

(defconst yeetube--buffer-name "*yeetube*"
  "Name of the buffer displaying search results.")

(defvar yeetube-items nil
  "List of scraped item plists.")

(defvar-local yeetube--continuation nil
  "Continuation plist for pagination.")

(defvar-local yeetube-mpv-no-video nil
  "Non-nil means disable video playback in the current YeeTube buffer.")

;; Switch var yeetube-mpv-enable-torsocks is auto-generated by the
;; yeetube-settings-map definition below.

(defvar-local yeetube--results-limit nil
  "Buffer-local results limit.")

(defvar-local yeetube-mpv-video-quality nil
  "Buffer-local video quality.")

(defvar-local yeetube--download-directory nil
  "Buffer-local download directory.")

(defvar-local yeetube--audio-format nil
  "Buffer-local audio format.")

(defvar yeetube-saved-videos nil
  "Saved/bookmarked video urls.")

(defvar yeetube-history nil
  "Stored urls & titles of recently played content.")

(defvar yeetube-search-history nil
  "History of search terms.")

(defcustom yeetube-request-headers
  '(("Accept-Language" . "en-US,en;q=0.9")
    ("Accept" . "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8")
    ("User-Agent" . "Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0")
    ("Cookie" . "ucbcb=1; gdpr=1; cookieconsent_status=allow"))
  "HTTP request headers sent on every yeetube fetch.
Bound around `url-retrieve' as `url-request-extra-headers'.  The
default `Cookie' header bypasses YouTube's EU cookie-consent
redirect via `ucbcb=1', plus the broader `gdpr=1' /
`cookieconsent_status=allow' pair for any CMP we land on.  Adjust
`Accept-Language' to bias responses to your locale."
  :type '(alist :key-type string :value-type string))


;;; Helpers

(defun yeetube--find-item (id)
  "Find item plist with ID in `yeetube-items'."
  (cl-find id yeetube-items
           :key (lambda (item) (plist-get item :id))
           :test #'equal))

(defmacro yeetube-with-tor-socks (&rest body)
  "Execute BODY, routed through tor when `yeetube-enable-tor' is non-nil."
  `(let ((url-gateway-method (if yeetube-enable-tor 'socks url-gateway-method))
         (socks-noproxy (if yeetube-enable-tor '("localhost") socks-noproxy))
         (socks-server (if yeetube-enable-tor
                           '("Default server" "127.0.0.1" 9050 5)
                         socks-server)))
     ,@body))

;; Function wrapper for use from other modules: the macro above is not
;; available when they are byte-compiled, a call here resolves at runtime.
(defun yeetube--queue-retrieve (url callback cbargs)
  "Queue retrieval of URL, calling CALLBACK with CBARGS.
Routed through tor when `yeetube-enable-tor' is non-nil."
  (yeetube-with-tor-socks
   (url-queue-retrieve url callback cbargs 'silent 'inhibit-cookies)))

(defun yeetube--fetch (request callback &optional cbargs)
  "Retrieve REQUEST asynchronously, then call CALLBACK with CBARGS.
REQUEST is a plist (:url U :method M :headers H :data D) as returned
by the `yeetube-backend-*-request' generics; only :url is required.
Request headers are appended after `yeetube-request-headers', so
they can add headers but not override the defaults.  Routed
through tor when `yeetube-enable-tor' is non-nil."
  (let ((url-request-method (or (plist-get request :method) "GET"))
        (url-request-extra-headers (append yeetube-request-headers
                                           (plist-get request :headers)))
        (url-request-data (plist-get request :data)))
    (yeetube-with-tor-socks
     (url-retrieve (plist-get request :url) callback cbargs
                   'silent 'inhibit-cookies))))

(defun yeetube-get-url (&optional id type)
  "Get video or playlist URL for entry ID, adjusted for TYPE."
  (let* ((id (or id (tabulated-list-get-id)))
         (item (yeetube--find-item id))
         (type (or type (plist-get item :type) 'video)))
    (yeetube-backend-item-url yeetube-backend id type)))

(defun yeetube-channel-id-at-point ()
  "Return yeetube channel id at point."
  (when (derived-mode-p 'yeetube-mode)
    (let* ((id (tabulated-list-get-id))
           (item (yeetube--find-item id)))
      (plist-get item :channel-id))))

(defun yeetube--browse-id-at-point ()
  "Return backend browse ID for the item at point.
Dormant infrastructure: consumed by the future `yeetube-home'
feed view (see `yeetube-display-feed')."
  (let* ((id (tabulated-list-get-id))
         (item (yeetube--find-item id)))
    (plist-get item :browse-id)))

(defun yeetube-read-query ()
  "Interactively read a search term."
  (read-string "Yeetube Search: " nil 'yeetube-search-history))

(defun yeetube--display-loading ()
  "Pop to the results buffer and show a loading indicator."
  (pop-to-buffer-same-window yeetube--buffer-name)
  (let ((inhibit-read-only t))
    (erase-buffer)
    (insert (propertize "Loading..." 'face 'bold-italic))))


;;; Playback

;;;###autoload
(defun yeetube-play ()
  "Play video at point in *yeetube* buffer."
  (interactive)
  (let* ((id (tabulated-list-get-id))
         (item (yeetube--find-item id))
         (url (yeetube-get-url id (plist-get item :type)))
         (title (plist-get item :title))
         (proc (apply yeetube-play-function url
                      (and yeetube-mpv-modeline-mode (list title)))))
    (when (processp proc)
      (process-put proc :now-playing title))
    (push (list :url url :title title) yeetube-history)
    (message "Playing: %s" title)))

;;;###autoload
(defun yeetube-copy-url ()
  "Copy entry URL at point."
  (interactive)
  (cl-assert (derived-mode-p 'yeetube-mode) nil "Yeetube mode not enabled")
  (let ((url (yeetube-get-url)))
    (kill-new url)
    (message "Copied url: %s" url)))

;;;###autoload
(defun yeetube-copy-rss-feed-url ()
  "Copy the RSS feed URL for the channel at point."
  (interactive)
  (cl-assert (derived-mode-p 'yeetube-mode) nil "Yeetube mode not enabled")
  (let* ((item (yeetube--find-item (tabulated-list-get-id)))
         (browse-id (plist-get item :browse-id))
         (url (and browse-id (not (string-empty-p browse-id))
                   (yeetube-backend-feed-url yeetube-backend browse-id))))
    (if url
        (progn (kill-new url)
               (message "Copied RSS feed: %s" url))
      (message "No channel ID available for this entry"))))

;;;###autoload
(defun yeetube-replay ()
  "Select entry from history to replay.

Select entry title from `yeetube-history' and play corresponding URL."
  (interactive)
  (let* ((titles (mapcar (lambda (entry) (plist-get entry :title)) yeetube-history))
         (selected (completing-read "Replay: " titles nil t))
         (selected-entry (cl-find-if (lambda (entry)
				       (string= selected (plist-get entry :title)))
				     yeetube-history))
	 (title (or (plist-get selected-entry :title)
                    (user-error "Unknown replay entry: %s" selected)))
         (url (plist-get selected-entry :url)))
    (funcall yeetube-play-function url (and yeetube-mpv-modeline-mode title))
    (message "Replaying: %s" selected)))

;;;###autoload
(defun yeetube-browse-url ()
  "Open entry at point in a web browser.
The YouTube backend browses videos through an invidious instance
from `yeetube-youtube-invidious-instances'."
  (interactive)
  (let* ((id (tabulated-list-get-id))
         (item (yeetube--find-item id))
         (type (or (plist-get item :type) 'video)))
    (browse-url (yeetube-backend-browse-url yeetube-backend id type))))


;;; Bookmarks

(defun yeetube-load-saved-videos ()
  "Load saved videos.
If the bookmark file is empty or unreadable, reset
`yeetube-saved-videos' to nil and emit a warning."
  (let ((file-path (locate-user-emacs-file "yeetube")))
    (if (file-exists-p file-path)
	(with-temp-buffer
	  (insert-file-contents file-path)
	  (goto-char (point-min))
	  (setf yeetube-saved-videos
		(condition-case nil
		    (read (current-buffer))
		  (error
		   (display-warning
		    'yeetube "Bookmark file unreadable; resetting saved videos")
		   nil))))
      (write-region "nil" nil file-path))))

;;;###autoload
(defun yeetube-save-video (arg)
  "Save url at point.

If ARG is non-nil, save as a playlist URL."
  (interactive "P")
  (yeetube-load-saved-videos)
  (let ((name (read-string "Save as: "))
	(url (yeetube-get-url (tabulated-list-get-id) (if arg 'playlist 'video))))
    (push (cons name url) yeetube-saved-videos)
    (yeetube-save-saved-videos)))

;; We could use keywords here, but it would break users saved videos
;; from previous versions.
;;;###autoload
(defun yeetube-play-saved-video ()
  "Select & Play a saved video."
  (interactive)
  (yeetube-load-saved-videos)
  (let* ((video (completing-read "Select video: " yeetube-saved-videos nil t))
         (entry (assoc video yeetube-saved-videos))
         (title (car entry))
         (url (cdr entry)))
    (funcall yeetube-play-function url (and yeetube-mpv-modeline-mode title))
    (message "Playing: %s" title)))

;;;###autoload
(defun yeetube-remove-saved-video ()
  "Select video to remove from saved videos."
  (interactive)
  (yeetube-load-saved-videos)
  (let ((video (completing-read "Select video: " yeetube-saved-videos nil t)))
    (setf yeetube-saved-videos (remq (assoc video yeetube-saved-videos) yeetube-saved-videos))
    (yeetube-save-saved-videos)))

;;;###autoload
(defun yeetube-remove-all-saved-videos ()
  "Clear all saved videos from yeetube."
  (interactive)
  (when (y-or-n-p "Delete saved?")
    (setf yeetube-saved-videos nil)
    (yeetube-save-saved-videos)))

(defun yeetube-save-saved-videos ()
  "Write `yeetube-saved-videos' to disk."
  (let ((file-path (locate-user-emacs-file "yeetube")))
    (with-temp-buffer
      (insert (pp-to-string yeetube-saved-videos))
      (write-region (point-min) (point-max) file-path))))


;;; Download

;;;###autoload
(defun yeetube-download-video (&optional url)
  "Download entry at point in *yeetube* buffer with yt-dlp.

Content will be downloaded at `yeetube-download-directory'.
Optionally, provide custom own URL."
  (interactive)
  (let* ((id (tabulated-list-get-id))
         (item (yeetube--find-item id))
         (type (plist-get item :type))
         (url (or url (yeetube-get-url id type)))
         (title (or (plist-get item :title) "Unknown")))
    (when (string-prefix-p "http" url)
      (let ((default-directory (or yeetube--download-directory
                                   yeetube-download-directory)))
        (yeetube-download--ytdlp url nil (or yeetube--audio-format
                                             yeetube-download-audio-format))
        (message "Downloading: '%s' at '%s'" title default-directory)))))


;;; Search & Callbacks

(defun yeetube--render-items (items limit &optional continuation)
  "Render ITEMS into the *yeetube* buffer with LIMIT and CONTINUATION.
Pops to the buffer per `yeetube-pop-to-same-window-p', resets the
major mode, populates state, and kicks off thumbnail fetching."
  (let ((pop-fn (if yeetube-pop-to-same-window-p
                    #'pop-to-buffer-same-window
                  #'pop-to-buffer)))
    (funcall pop-fn yeetube--buffer-name)
    ;; Enabling the mode kills buffer-locals, so re-renders must not
    ;; reset settings like video quality or download directory.
    (unless (derived-mode-p 'yeetube-mode)
      (yeetube-mode))
    (setq yeetube-items items)
    (setq-local yeetube--continuation continuation)
    (setq-local yeetube--results-limit limit)
    (yeetube-ui-render items)
    (yeetube-ui-fetch-thumbnails items yeetube--buffer-name)))

(defun yeetube--current-limit ()
  "Return the active results limit, reading from the *yeetube* buffer."
  (let ((buf (get-buffer yeetube--buffer-name)))
    (or (and buf (buffer-local-value 'yeetube--results-limit buf))
        yeetube-results-limit)))

(defun yeetube--decode-url-buffer (url-buffer)
  "Insert URL-BUFFER's body into the current buffer, decoded as UTF-8.
Call from inside a `with-temp-buffer' so the inserted text is
scoped to a throwaway buffer for parsing."
  (set-buffer-multibyte t)
  (url-insert url-buffer)
  (decode-coding-region (point-min) (point-max) 'utf-8))

(defconst yeetube--parse-error-message "Could not parse backend response"
  "Message shown when a backend response cannot be parsed.")

(defconst yeetube--retrieve-error-message "Could not retrieve backend response"
  "Message shown when a backend response could not be retrieved.")

(defconst yeetube--empty-results-message "No videos found"
  "Message shown when a successful response contains no videos.")

(defconst yeetube--no-more-results-message "No more videos found"
  "Message shown when a continuation response contains no videos.")

(defun yeetube--show-response-error (message &optional detail)
  "Report response failure MESSAGE to the user.
Clear an active loading indicator without erasing existing results.
DETAIL is an optional diagnostic string."
  (when-let* ((buffer (get-buffer yeetube--buffer-name)))
    (with-current-buffer buffer
      (when (string-match-p "\\`Loading" (buffer-string))
        (let ((inhibit-read-only t))
          (erase-buffer)
          (insert message)))))
  (if detail
      (message "%s: %s" message detail)
    (message "%s" message)))

(defun yeetube--show-parse-error (&optional detail)
  "Report a backend parse failure with optional DETAIL."
  (yeetube--show-response-error yeetube--parse-error-message detail))

(defun yeetube--parse-response (status parser)
  "Return PARSER's result on the current URL response buffer.
The response buffer is killed afterwards.  Return nil when STATUS
carries an error.  PARSER is called from a temporary buffer holding
the decoded response body."
  (let ((url-buffer (current-buffer)))
    (unwind-protect
        (if-let* ((status-error (plist-get status :error)))
            (progn
              (yeetube--show-response-error
               yeetube--retrieve-error-message
               (error-message-string status-error))
              nil)
          (condition-case err
              (with-temp-buffer
                (yeetube--decode-url-buffer url-buffer)
                (funcall parser))
            (error
             (yeetube--show-parse-error (error-message-string err))
             nil)))
      (kill-buffer url-buffer))))

(defun yeetube--page-callback (status)
  "Render a parsed results page from a URL response with STATUS."
  (let* ((limit (yeetube--current-limit))
         (result (yeetube--parse-response
                  status
                  (lambda () (yeetube-backend-parse-page yeetube-backend))))
         (items (plist-get result :items)))
    (cond (items
           (yeetube--render-items items limit (plist-get result :continuation))
           (yeetube--auto-paginate limit))
          (result
           (yeetube--show-response-error yeetube--empty-results-message)))))

(defun yeetube--feed-callback (status &optional fallback-url)
  "Render channel feed items from a URL response with STATUS.
When the feed yields nothing, fall back to displaying FALLBACK-URL
with the regular page parser."
  (let ((items (ignore-errors
                 (yeetube--parse-response
                  status
                  (lambda () (yeetube-backend-parse-feed yeetube-backend))))))
    (cond (items (yeetube--render-items items (yeetube--current-limit)))
          ((plist-get status :error)
           (when fallback-url (yeetube-display-content-from-url fallback-url)))
          (fallback-url
           (message "No feed videos found")
           (yeetube-display-content-from-url fallback-url))
          (t (message "No feed videos found")))))

(defun yeetube-display-feed (channel &optional fallback-url)
  "Display CHANNEL's videos from the backend's feed.
When the feed fails, display FALLBACK-URL with the regular parser.
Dormant infrastructure for the upcoming `yeetube-home'
subscription view; `yeetube-channel-videos' scrapes the HTML
videos tab instead, which is the only way to get duration/views
and to paginate past YouTube's 15-entry RSS cap."
  (let ((url (yeetube-backend-feed-url yeetube-backend channel)))
    (unless url
      (user-error "Backend `%s' does not provide feeds" yeetube-backend))
    (yeetube--fetch (list :url url) #'yeetube--feed-callback
                    (and fallback-url (list fallback-url)))))

(defun yeetube-display-content-from-url (url)
  "Display the video results from URL."
  (yeetube--fetch (list :url url) #'yeetube--page-callback))

;;;###autoload
(defun yeetube-search (query)
  "Search for QUERY."
  (interactive (list (yeetube-read-query)))
  (yeetube--display-loading)
  (yeetube--fetch (yeetube-backend-search-request yeetube-backend query)
                  #'yeetube--page-callback))


;;; Pagination

(defun yeetube--auto-paginate (limit)
  "Automatically fetch next page if current items are below LIMIT."
  (when (and yeetube--continuation
             (length< yeetube-items limit))
    (yeetube-next-page)))

;;;###autoload
(defun yeetube-next-page ()
  "Fetch and append the next page of results."
  (interactive)
  (unless yeetube--continuation
    (user-error "No more results"))
  (yeetube--fetch
   (yeetube-backend-continuation-request yeetube-backend yeetube--continuation)
   #'yeetube--continuation-callback))

(defun yeetube--continuation-callback (status)
  "Append the parsed next page from a URL response with STATUS."
  (let* ((result (yeetube--parse-response
                  status
                  (lambda () (yeetube-backend-parse-continuation yeetube-backend))))
         (items (plist-get result :items)))
    (cond
     (items
      (with-current-buffer yeetube--buffer-name
        (setq yeetube-items (append yeetube-items items))
        (setq-local yeetube--continuation (plist-get result :continuation))
        (yeetube-ui-append items)
        (yeetube-ui-fetch-thumbnails items yeetube--buffer-name)
        (yeetube--auto-paginate (yeetube--current-limit))))
     (result
      (with-current-buffer yeetube--buffer-name
        (setq-local yeetube--continuation nil))
      (yeetube--show-response-error yeetube--no-more-results-message)))))


;;; Channel browsing

(defun yeetube--display-channel (channel what &optional query)
  "Fetch and display CHANNEL's WHAT content.
WHAT is `videos', `streams', or `search' with a QUERY string."
  (unless (and (stringp channel)
               (not (string-empty-p (string-trim channel))))
    (user-error "No channel ID available"))
  (let ((channel (string-trim channel)))
    (message "Fetching channel %s" channel)
    (yeetube--fetch
     (yeetube-backend-channel-request yeetube-backend channel what query)
     #'yeetube--page-callback)))

;;;###autoload
(defun yeetube-channel-videos (&optional channel-id)
  "View videos for the channel with CHANNEL-ID."
  (interactive (list (or (yeetube-channel-id-at-point)
                         (yeetube-backend-read-channel yeetube-backend))))
  (yeetube--display-channel channel-id 'videos))

;;;###autoload
(defun yeetube-channel-streams (&optional channel-id)
  "View streams for the channel with CHANNEL-ID."
  (interactive (list (or (yeetube-channel-id-at-point)
                         (yeetube-backend-read-channel yeetube-backend))))
  (yeetube--display-channel channel-id 'streams))

(defun yeetube-channel-search (channel-id query)
  "Search channel with CHANNEL-ID for videos matching QUERY."
  (interactive (list (or (yeetube-channel-id-at-point)
                         (yeetube-backend-read-channel yeetube-backend))
                     (yeetube-read-query)))
  (yeetube--display-channel channel-id 'search query))


;;; Mode

(defun yeetube--read-video-quality (prompt)
  "Read video quality with PROMPT."
  (completing-read prompt '("1080" "720" "480" "360" "240" "144") nil t))

(defun yeetube--read-audio-format (prompt)
  "Read audio format with PROMPT."
  (let ((choice (completing-read prompt
				 '("none" "aac" "alac" "flac" "m4a" "mp3" "opus" "vorbis" "wav")
				 nil t)))
    (if (equal choice "none") nil choice)))

(defun yeetube-set-results-limit ()
  "Set results limit."
  (interactive)
  (setq-local yeetube--results-limit (read-number "Results limit: "))
  (message "Results limit: %s" yeetube--results-limit))

(defun yeetube-set-video-quality ()
  "Set video quality."
  (interactive)
  (setq-local yeetube-mpv-video-quality (yeetube--read-video-quality "Video quality: "))
  (message "Video quality: %s" yeetube-mpv-video-quality))

(defun yeetube-set-download-directory ()
  "Set download directory."
  (interactive)
  (setq-local yeetube--download-directory (read-directory-name "Download dir: "))
  (message "Download dir: %s" yeetube--download-directory))

(defun yeetube-set-audio-format ()
  "Set audio format."
  (interactive)
  (setq-local yeetube--audio-format (yeetube--read-audio-format "Audio format: "))
  (message "Audio format: %s" (or yeetube--audio-format "none")))

(defun yeetube--setting-desc (label value)
  "Return LABEL and VALUE formatted for popup display."
  (format "%s: %s" label
          (propertize (format "%s" value) 'face 'font-lock-constant-face)))

(keymap-popup-define yeetube-settings-map
  "Yeetube settings menu."
  :description "Yeetube Settings"
  :group "Session"
  "l" ((lambda () (yeetube--setting-desc
                   "Results limit" (or yeetube--results-limit
                                       yeetube-results-limit)))
       yeetube-set-results-limit :stay-open t)
  "v" ((lambda () (yeetube--setting-desc
                   "Video quality" (or yeetube-mpv-video-quality "default")))
       yeetube-set-video-quality :stay-open t)
  "d" ((lambda () (yeetube--setting-desc
                   "Download dir" (or yeetube--download-directory
                                      yeetube-download-directory)))
       yeetube-set-download-directory :stay-open t)
  "a" ((lambda () (yeetube--setting-desc
                   "Audio format" (or yeetube--audio-format "none")))
       yeetube-set-audio-format :stay-open t)
  :group "Switches"
  "n" ("No video" :switch yeetube-mpv-no-video)
  "t" ("Torsocks" :switch yeetube-mpv-enable-torsocks))

(keymap-popup-define yeetube-mode-map
  "Yeetube Mode Map"
  :description "Yeetube Menu"
  :group "Play"
  "RET" ("Play" yeetube-play)
  "r" ("Replay" yeetube-replay)
  "P" ("Play saved" yeetube-play-saved-video)
  :group "Navigate"
  "s" ("Search" yeetube-search)
  "M-n" ("Next page" yeetube-next-page)
  "c" ("Channel videos" yeetube-channel-videos)
  "L" ("Channel streams" yeetube-channel-streams)
  :group "Playback"
  "p" ("Toggle pause" yeetube-mpv-toggle-pause :inapt-if #'yeetube-mpv--idle-p)
  "v" ("Toggle video" yeetube-mpv-toggle-video :inapt-if #'yeetube-mpv--idle-p)
  :group "Actions"
  "S" ("Save video" yeetube-save-video)
  "C" ("Copy URL" yeetube-copy-url)
  "R" ("Copy RSS feed" yeetube-copy-rss-feed-url)
  "b" ("Browse (invidious)" yeetube-browse-url)
  "d" ("Download" yeetube-download-video)
  "o" ("Settings" :keymap yeetube-settings-map)
  "q" ("Quit" quit-window))

(define-derived-mode yeetube-mode tabulated-list-mode "Yeetube"
  "Yeetube mode."
  :keymap yeetube-mode-map
  (setq-local truncate-string-ellipsis " ")
  ;; Set defaults for macro-generated buffer-local vars
  (unless yeetube--results-limit
    (setq-local yeetube--results-limit yeetube-results-limit))
  (unless yeetube-mpv-video-quality
    (setq-local yeetube-mpv-video-quality "720"))
  (unless yeetube--download-directory
    (setq-local yeetube--download-directory yeetube-download-directory))
  (unless yeetube--audio-format
    (setq-local yeetube--audio-format yeetube-download-audio-format))
  (setq-local yeetube-mpv-no-video
              (member "--no-video" yeetube-mpv-additional-flags))
  (display-line-numbers-mode 0))

;;;###autoload
(defun yeetube ()
  "YeeTube entrypoint."
  (interactive)
  (keymap-popup yeetube-mode-map))

(provide 'yeetube)
;;; yeetube.el ends here
